image: maven:latest

before_script:
  - echo "deb http://packages.cloud.google.com/apt cloud-sdk-jessie main" | tee /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  - apt-get update && apt-get install google-cloud-sdk -y && apt-get install google-cloud-sdk-app-engine-java -y

after_script:
  - rm /tmp/auth.json

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - echo $AUTH
    - echo $AUTH > /tmp/auth.json
    - mvn install
    - gcloud auth activate-service-account --key-file='/tmp/auth.json'
    - gcloud --quiet --project "comillas-221409" app deploy /builds/pablo627/testGCloud/target/testGoogle-0.0.1-SNAPSHOT.war
